version: '3.8'

services:
  vanna-ai:
    build: .
    ports:
      - "9000:8000"  # Backend API (9000 external -> 8000 internal)
      - "9001:8501"  # Frontend UI (9001 external -> 8501 internal)
    labels:
      - "coolify.port=8501"  # Tell Coolify to proxy to the frontend port
    environment:
      # Database connection
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SESSION_DATABASE_URL: ${SESSION_DATABASE_URL}
      
      # Qdrant Cloud
      QDRANT_URL: ${QDRANT_URL}
      QDRANT_API_KEY: ${QDRANT_API_KEY}
      
      # Optional: Set Python unbuffered for better logs
      PYTHONUNBUFFERED: "1"
    
    volumes:
      # Persist model storage and connections
      - vanna_storage:/app/vanna_storage
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  vanna_storage:
    driver: local 